# Generated by Django 5.0.14 on 2026-07-20 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("link", "link"), ("file", "file")], max_length=10
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(blank=True)),
                ("file", models.BinaryField(blank=True, null=True)),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_resources",
                "ordering": ["-created_at"],
            },
        ),
    ]
