# Generated by Django 5.0.14 on 2026-07-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="target_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
