# Generated by Django 5.1.4 on 2026-07-18 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('card_label', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=8)),
                ('renews_on', models.DateField()),
                ('source_url', models.URLField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'manual'), ('extension', 'extension')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_platforms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'linked_platforms',
                'ordering': ['renews_on'],
            },
        ),
    ]
